### ISSUE TITLE
Travis checker for peering info

### ISSUE THREAD

**Issue by Kubuxu** [hyperboria/peers#18] opened 2015-11-25 20:30 UTC
Iterate all files, load them as JSON, bencode them and check size. Just to have correct peering info. Also we could require essential and contact info in the peer file.

**Comment by thefinn93** [comment] 2015-11-25 20:35
duplicate of #7?

**Comment by Kubuxu** [comment] 2015-11-25 20:45
It could a part of it. Main reason would be to check incoming PRs.

**Closed** 2015-11-25 21:51 UTC
